# Generated by Django 2.1.1 on 2018-09-29 07:41

import blogapp.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('text', models.TextField()),
                ('article_title', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('register_date', models.DateTimeField(verbose_name='date registered')),
                ('user_name', models.CharField(max_length=50)),
                ('user_pass', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(upload_to=blogapp.models.user_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogapp.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Comment'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Question'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogapp.User'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Comment'),
        ),
    ]
