# Generated by Django 2.1.1 on 2018-10-01 05:33

import blogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20180929_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=blogapp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pass',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
