# Generated by Django 2.1.1 on 2018-10-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_posttopic_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttopic',
            name='articles',
        ),
        migrations.AddField(
            model_name='posttopic',
            name='articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.BlogPost'),
        ),
    ]
