# Generated by Django 2.1.1 on 2018-10-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_blogpost_is_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AskPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='askanswer',
            name='question_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.AskPost'),
        ),
    ]
