# Generated by Django 2.1.2 on 2019-01-16 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_auto_20181016_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenews',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 4, 50, 6, 468287, tzinfo=utc), verbose_name='date published'),
        ),
    ]
