# Generated by Django 2.1.5 on 2019-01-16 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_auto_20190116_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='sitenews',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 5, 24, 56, 987614, tzinfo=utc), verbose_name='date published'),
        ),
    ]
