# Generated by Django 2.1.5 on 2019-01-16 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_auto_20190116_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenews',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 6, 33, 37, 376772, tzinfo=utc), verbose_name='date published'),
        ),
    ]
