# Generated by Django 2.1.5 on 2019-01-22 05:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0024_auto_20190116_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenews',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 5, 0, 44, 293746, tzinfo=utc), verbose_name='date published'),
        ),
    ]
