# Generated by Django 2.1.5 on 2019-01-26 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0026_auto_20190126_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenews',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 26, 18, 25, 0, 207400, tzinfo=utc), verbose_name='date published'),
        ),
    ]
