# Generated by Django 2.1.1 on 2018-10-09 03:05

import blogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20181004_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='askpost',
            name='question_title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.ManyToManyField(default=[blogapp.models.BlogPost.defaultTag], to='blogapp.PostTopic'),
        ),
    ]
