# Generated by Django 2.1.1 on 2018-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20181009_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askanswer',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='askpost',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
