# Generated by Django 2.1.1 on 2018-10-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20181009_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='askanswer',
            name='is_posted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='askpost',
            name='is_posted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_posted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='is_posted',
            field=models.BooleanField(default=True),
        ),
    ]
