# Generated by Django 2.1.2 on 2018-10-16 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_auto_20181016_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenews',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 1, 13, 12, 826118, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='sitenews',
            name='tag',
            field=models.TextField(),
        ),
    ]
